language: node_js
node_js:
  - stable
  - 8
cache:
  directories:
    - "node_modules"
before_deploy:
  - npm run lint
  - npm run build
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    file:
      - './src/SwipeRow/SwipeRow.js'
      - './package.json'
    on:
      tags: true
  - provider: pages
    local_dir: './build'
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master
  - provider: npm
    email: thanatos1710@gmail.com
    api_key: $NPM_TOKEN
    on:
      tags: true
